import Sidebar from "../components/Sidebar";
import StatCard from "../components/StatCard";

import jsPDF from "jspdf";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";

function Dashboard() {
  // LOAD DATA

  const orders =
    JSON.parse(localStorage.getItem("orders")) || [];

  const customers =
    JSON.parse(localStorage.getItem("customers")) ||
    [];

  const inventory =
    JSON.parse(localStorage.getItem("inventory")) ||
    [];

  // CALCULATIONS

  const totalOrders = orders.length;

  const pendingPayments = orders
    .filter((order) => order.status !== "Paid")
    .reduce((total, order) => {
      return total + order.amount;
    }, 0);

  const totalCustomers = customers.length;

  const lowStockItems = inventory.filter(
    (item) => item.quantity <= item.threshold
  ).length;

  // DOWNLOAD PDF REPORT

  const downloadReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);

    doc.text(
      "HisabKitab Business Report",
      20,
      20
    );

    doc.setFontSize(14);

    doc.text(
      `Total Orders: ${totalOrders}`,
      20,
      50
    );

    doc.text(
      `Pending Payments: ₹${pendingPayments}`,
      20,
      70
    );

    doc.text(
      `Customers: ${totalCustomers}`,
      20,
      90
    );

    doc.text(
      `Low Stock Items: ${lowStockItems}`,
      20,
      110
    );

    doc.text(
      "Generated by HisabKitab AI",
      20,
      150
    );

    doc.save("HisabKitab_Report.pdf");
  };

  // CHART DATA

  const salesData = [
    { month: "Jan", sales: 4000 },
    { month: "Feb", sales: 3000 },
    { month: "Mar", sales: 5000 },
    { month: "Apr", sales: 4500 },
    { month: "May", sales: 6000 },
  ];

  const paidOrders = orders.filter(
    (order) => order.status === "Paid"
  ).length;

  const pendingOrders = orders.filter(
    (order) => order.status !== "Paid"
  ).length;

  const paymentData = [
    {
      name: "Paid",
      value: paidOrders,
    },
    {
      name: "Pending",
      value: pendingOrders,
    },
  ];

  const COLORS = ["#00C49F", "#FF8042"];

  return (
    <div style={{ display: "flex" }}>
      <Sidebar />

      <div
        style={{
          marginLeft: "250px",
          width: "100%",
          padding: "30px",
          color: "white",
        }}
      >
        <h1>HisabKitab Dashboard</h1>

        <p>
          Welcome back to your business overview.
        </p>

        {/* STAT CARDS */}

        <div
          style={{
            display: "flex",
            gap: "20px",
            flexWrap: "wrap",
            marginTop: "30px",
          }}
        >
          <StatCard
            title="Total Orders"
            value={totalOrders}
          />

          <StatCard
            title="Pending Payments"
            value={`₹${pendingPayments}`}
          />

          <StatCard
            title="Customers"
            value={totalCustomers}
          />

          <StatCard
            title="Low Stock Items"
            value={lowStockItems}
          />
        </div>

        {/* DOWNLOAD REPORT BUTTON */}

        <button
          onClick={downloadReport}
          style={{
            marginTop: "30px",
            padding: "14px 22px",
            backgroundColor: "#238636",
            color: "white",
            border: "none",
            borderRadius: "10px",
            cursor: "pointer",
            fontWeight: "bold",
            fontSize: "16px",
          }}
        >
          Download Business Report
        </button>

        {/* CHARTS */}

        <div
          style={{
            display: "flex",
            gap: "30px",
            flexWrap: "wrap",
            marginTop: "50px",
          }}
        >
          {/* SALES BAR CHART */}

          <div
            style={{
              backgroundColor: "#161b22",
              border: "1px solid #30363d",
              borderRadius: "12px",
              padding: "20px",
              width: "600px",
              minHeight: "350px",
            }}
          >
            <h2
              style={{
                marginBottom: "20px",
              }}
            >
              Monthly Sales
            </h2>

            <ResponsiveContainer
              width="100%"
              height={250}
            >
              <BarChart data={salesData}>
                <XAxis dataKey="month" />

                <YAxis />

                <Tooltip />

                <Bar
                  dataKey="sales"
                  fill="#58a6ff"
                />
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* PAYMENT PIE CHART */}

          <div
            style={{
              backgroundColor: "#161b22",
              border: "1px solid #30363d",
              borderRadius: "12px",
              padding: "20px",
              width: "350px",
              minHeight: "350px",
            }}
          >
            <h2
              style={{
                marginBottom: "20px",
              }}
            >
              Payment Status
            </h2>

            <ResponsiveContainer
              width="100%"
              height={250}
            >
              <PieChart>
                <Pie
                  data={paymentData}
                  cx="50%"
                  cy="50%"
                  outerRadius={100}
                  dataKey="value"
                  label
                >
                  {paymentData.map(
                    (entry, index) => (
                      <Cell
                        key={index}
                        fill={
                          COLORS[index % COLORS.length]
                        }
                      />
                    )
                  )}
                </Pie>

                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* AI INSIGHT */}

        <div
          style={{
            marginTop: "40px",
            backgroundColor: "#161b22",
            border: "1px solid #30363d",
            padding: "20px",
            borderRadius: "12px",
          }}
        >
          <h2>AI Business Insight</h2>

          <p>
            {lowStockItems > 0
              ? `⚠ ${lowStockItems} inventory items are running low.`
              : "✅ Inventory levels look healthy."}
          </p>

          <p
            style={{
              marginTop: "10px",
            }}
          >
            💡 AI predicts increased demand
            this weekend based on order
            trends.
          </p>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;