import Sidebar from "../components/Sidebar";
import StatCard from "../components/StatCard";
import jsPDF from "jspdf";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";

function Dashboard() {
  const orders =
    JSON.parse(localStorage.getItem("orders")) || [];

  const customers =
    JSON.parse(localStorage.getItem("customers")) ||
    [];

  const inventory =
    JSON.parse(localStorage.getItem("inventory")) ||
    [];

  const totalOrders = orders.length;

  const pendingPayments = orders
    .filter((order) => order.status !== "Paid")
    .reduce((total, order) => total + order.amount, 0);

  const totalRevenue = orders
    .filter((order) => order.status === "Paid")
    .reduce((total, order) => total + order.amount, 0);

  const totalCustomers = customers.length;

  const lowStockItems = inventory.filter(
    (item) => item.quantity <= item.threshold
  ).length;

  const downloadReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("HisabKitab Business Report", 20, 20);

    doc.setFontSize(14);
    doc.text(`Total Orders: ${totalOrders}`, 20, 50);
    doc.text(`Paid Revenue: Rs.${totalRevenue}`, 20, 70);
    doc.text(`Pending Payments: Rs.${pendingPayments}`, 20, 90);
    doc.text(`Customers: ${totalCustomers}`, 20, 110);
    doc.text(`Low Stock Items: ${lowStockItems}`, 20, 130);
    doc.text("Generated by HisabKitab AI", 20, 170);

    doc.save("HisabKitab_Report.pdf");
  };

  const paidOrders = orders.filter(
    (order) => order.status === "Paid"
  ).length;

  const pendingOrders = orders.filter(
    (order) => order.status !== "Paid"
  ).length;

  const salesData = [
    { month: "Jan", sales: 4000 },
    { month: "Feb", sales: 3000 },
    { month: "Mar", sales: 5000 },
    { month: "Apr", sales: 4500 },
    { month: "May", sales: 6000 },
  ];

  const paymentData = [
    { name: "Paid", value: paidOrders },
    { name: "Pending", value: pendingOrders },
  ];

  const COLORS = ["#31d47b", "#f5c84c"];
  const paymentHealth =
    totalOrders === 0
      ? 0
      : Math.round((paidOrders / totalOrders) * 100);

  return (
    <div className="app-shell">
      <Sidebar />

      <main className="page">
        <header className="page-header">
          <div>
            <p className="eyebrow">Business command center</p>
            <h1 className="page-title">Dashboard</h1>
            <p className="page-subtitle">
              See money pending, stock pressure and daily operating
              signals without digging through separate screens.
            </p>
          </div>

          <div className="hero-metric">
            <span>Payment health</span>
            <strong>{paymentHealth}%</strong>
            <div className="progress-track">
              <div
                className="progress-fill"
                style={{ width: `${paymentHealth}%` }}
              />
            </div>
          </div>
        </header>

        <section className="grid stats-grid">
          <StatCard
            title="Total Orders"
            value={totalOrders}
          />
          <StatCard
            title="Paid Revenue"
            value={`Rs.${totalRevenue}`}
          />
          <StatCard
            title="Pending Due"
            value={`Rs.${pendingPayments}`}
          />
          <StatCard
            title="Low Stock"
            value={lowStockItems}
          />
        </section>

        <div
          className="panel"
          style={{ marginTop: "22px" }}
        >
          <div className="card-head">
            <div>
              <h2>Quick report</h2>
              <p className="muted">
                Generate a compact PDF for your records or demo.
              </p>
            </div>

            <button
              onClick={downloadReport}
              className="btn btn-primary"
            >
              Download Report
            </button>
          </div>
        </div>

        <section
          className="grid content-grid"
          style={{ marginTop: "22px" }}
        >
          <div className="panel chart-card">
            <div className="card-head">
              <div>
                <h2>Monthly Sales</h2>
                <p className="muted">
                  A sample trend view for your pitch narrative.
                </p>
              </div>
            </div>

            <ResponsiveContainer
              width="100%"
              height={260}
            >
              <BarChart data={salesData}>
                <XAxis
                  dataKey="month"
                  stroke="#91a1b7"
                />
                <YAxis stroke="#91a1b7" />
                <Tooltip
                  contentStyle={{
                    background: "#111821",
                    border: "1px solid #334155",
                    borderRadius: "8px",
                    color: "white",
                  }}
                />
                <Bar
                  dataKey="sales"
                  fill="#4f8cff"
                  radius={[8, 8, 0, 0]}
                />
              </BarChart>
            </ResponsiveContainer>
          </div>

          <div className="panel chart-card">
            <div className="card-head">
              <div>
                <h2>Payment Status</h2>
                <p className="muted">
                  Paid vs pending orders at a glance.
                </p>
              </div>
            </div>

            <ResponsiveContainer
              width="100%"
              height={260}
            >
              <PieChart>
                <Pie
                  data={paymentData}
                  cx="50%"
                  cy="50%"
                  innerRadius={55}
                  outerRadius={95}
                  paddingAngle={4}
                  dataKey="value"
                  label
                >
                  {paymentData.map(
                    (entry, index) => (
                      <Cell
                        key={entry.name}
                        fill={
                          COLORS[index % COLORS.length]
                        }
                      />
                    )
                  )}
                </Pie>
                <Tooltip
                  contentStyle={{
                    background: "#111821",
                    border: "1px solid #334155",
                    borderRadius: "8px",
                    color: "white",
                  }}
                />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </section>

        <section
          className="panel ai-card"
          style={{ marginTop: "22px" }}
        >
          <p className="eyebrow">AI summary</p>
          <h2 style={{ marginTop: "8px" }}>
            {lowStockItems > 0
              ? `${lowStockItems} stock item needs attention.`
              : "Inventory levels look healthy."}
          </h2>
          <p
            className="muted"
            style={{ marginTop: "10px" }}
          >
            Combine payment reminders with restock suggestions to
            reduce cash blockage and avoid missed sales.
          </p>
        </section>
      </main>
    </div>
  );
}

export default Dashboard;
